import { report } from "process";

export const tagTypes = {
  auth: "Auth",
  terms: "Terms",
  about: "About",
  aboutHeroSection: "AboutHeroSection",
  freedomPathPlanning: "FreedomPathPlanning",
  aboutSteveDeray: "AboutSteveDeray",
  privacyPolicy: "PrivacyPolicy",
  profile: "Profile",
  users: "Users",
  dashboard: "Dashboard",
  earning: "Earning",
  subscription: "Subscription",
  content: "Content",
  services: "Services",
  associates: "Associates",
  testimonials: "Testimonials",
  toolResources: "ToolResources",
  bookResources: "BookResources",
  books: "Books",
  blogs: "Blogs",
  downloadBooks: "DownloadBooks",
  reports: "Reports",
  footerSection: "FooterSection",
  homePage: "HomePage",
  contactUs: "ContactUs",

};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.terms,
  tagTypes.about,
  tagTypes.aboutHeroSection,
  tagTypes.freedomPathPlanning,
  tagTypes.aboutSteveDeray,
  tagTypes.privacyPolicy,
  tagTypes.profile,
  tagTypes.users,
  tagTypes.dashboard,
  tagTypes.earning,
  tagTypes.subscription,
  tagTypes.content,
  tagTypes.services,
  tagTypes.associates,
  tagTypes.testimonials,
  tagTypes.toolResources,
  tagTypes.bookResources,
  tagTypes.books,
  tagTypes.blogs,
  tagTypes.downloadBooks,
  tagTypes.reports,
  tagTypes.footerSection,
  tagTypes.homePage,
  tagTypes.contactUs,
];


